name: Deploy to Fly.io

on:
  push:
    branches:
      - Tests # Rama desde la cual voy a desplegar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        # Verifica el código fuente del repositorio

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"
        # Configura Node.js 14 en el entorno de ejecución

      - name: Install Meteor
        run: curl https://install.meteor.com/?release=2.12 | sh
        # Instala Meteor 2.12

      - name: Build application
        run: |
          meteor npm install --production
          rm -rf /build  # Limpia el directorio de construcción (si existe)
          meteor build --directory /build --server-only
        # Construye la aplicación Meteor

      - name: Install Flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
        # Instala Flyctl

      - name: Authenticate with Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl auth token $FLY_API_TOKEN
        # Autentica Flyctl con el token de API

      - name: Deploy to Fly.io
        run: |
          flyctl deploy --config fly.toml --remote-only --build-arg NODE_ENV=production
        # Despliega la aplicación usando Flyctl con variables de entorno adecuadas

      - name: Verify deployment
        run: |
          flyctl status
        # Verifica el estado del despliegue
