# fly.toml

[app]
name = "api_dev"  # Nombre de tu aplicación

[build]
dockerfile = "Dockerfile"  # Especifica el Dockerfile 

[[services]]
internal_port = 8080
external_port = 80

[env]
NODE_ENV = "production"
