name: Test Workflow for Fly.io Deployment
#test
on:
  push:
    branches:
      - tests # Rama desde la cual quieres ejecutar las pruebas

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        # Verifica el código fuente del repositorio

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"
        # Configura Node.js 14 en el entorno de ejecución

      - name: Install Meteor
        run: curl https://install.meteor.com/?release=2.12 | sh
        # Instala Meteor 2.12

      - name: Install dependencies
        run: |
          meteor npm install
        # Instala las dependencias de la aplicación

      - name: Run server tests
        run: |
          meteor test --driver-package meteortesting:mocha --port 3100
        # Ejecuta las pruebas del servidor directamente
